language: cpp
before_install:
    - git clone git://github.com/brpylko/wpilib.git ~/wpilib
    - sudo add-apt-repository -y ppa:byteit101/frc-toolchain
    - sudo apt-get update
install:
    - sudo apt-get install frc-toolchain
script:
    - make
